# Generated by Django 2.0.3 on 2020-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200625_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='typeOfPizza',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], max_length=1),
        ),
    ]
