# Generated by Django 2.1.5 on 2020-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dinnerplatters_pasta_salads_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatters',
            name='image',
            field=models.ImageField(blank=True, upload_to='DinnerPlatters'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='image',
            field=models.ImageField(blank=True, upload_to='pasta'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='pizza'),
        ),
        migrations.AlterField(
            model_name='salads',
            name='image',
            field=models.ImageField(blank=True, upload_to='salada'),
        ),
        migrations.AlterField(
            model_name='subs',
            name='image',
            field=models.ImageField(blank=True, upload_to='subs'),
        ),
    ]
