# Generated by Django 2.1.5 on 2020-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200701_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Preparing'), ('F', 'Completed'), ('C', 'Canceled')], max_length=1),
        ),
    ]
