# Generated by Django 2.1.5 on 2020-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200701_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='orderitemtype',
            field=models.CharField(default='food', max_length=100),
        ),
    ]
