# Generated by Django 2.1.5 on 2020-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitems_orderitemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='selectedtoppings',
            field=models.ManyToManyField(to='orders.Toppings'),
        ),
    ]
