# Generated by Django 3.0 on 2020-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_bookingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
