# Generated by Django 3.0 on 2020-07-17 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200716_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='apartmentNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='checkoutEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='orders',
            name='companyName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 11, 55, 51, 873799)),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 17, 11, 55, 51, 873799)),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryTimeType',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryType',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='floorNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentType',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='orders',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='streetNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
