# Generated by Django 3.0 on 2020-07-17 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200717_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 12, 51, 27, 279613)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 17, 12, 51, 27, 279613)),
        ),
    ]
