# Generated by Django 3.0 on 2020-08-01 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200717_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 5, 39, 15, 168129)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 1, 5, 39, 15, 168129)),
        ),
    ]
