# Generated by Django 2.1.5 on 2020-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typeOf', models.CharField(choices=[('V', 'Vegetables'), ('F', 'Fruits'), ('J', 'Juice'), ('D', 'Dried Fruits')], max_length=1)),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='items')),
                ('dealOfTheDay', models.BooleanField()),
            ],
        ),
    ]
