# Generated by Django 3.0 on 2020-09-12 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0011_auto_20200911_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 12, 5, 47, 53, 934470)),
        ),
    ]
