# Generated by Django 3.0 on 2020-09-12 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0012_auto_20200912_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 12, 5, 56, 28, 69160)),
        ),
        migrations.AlterField(
            model_name='items',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
