# Generated by Django 3.0 on 2020-08-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
