# Generated by Django 3.0 on 2020-09-01 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_items_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('discountpercent', models.IntegerField()),
                ('discountamount', models.FloatField()),
                ('createdDate', models.DateField(default=datetime.datetime(2020, 9, 1, 9, 20, 11, 95115))),
                ('endDate', models.DateField()),
            ],
        ),
    ]
