# Generated by Django 3.0 on 2020-09-01 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 11, 51, 59, 461241)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discountamount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discountpercent',
            field=models.IntegerField(default=0),
        ),
    ]
