# Generated by Django 3.0 on 2020-09-02 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0004_auto_20200901_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('houseAddress', models.CharField(max_length=100)),
                ('appartmentNumber', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('paymentType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 9, 51, 47, 119400)),
        ),
    ]
