# Generated by Django 3.0 on 2020-09-02 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0005_auto_20200902_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='subTotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='totalPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 33, 2, 787612)),
        ),
        migrations.CreateModel(
            name='cartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('quantitty', models.IntegerField()),
                ('totalPrice', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orderitems.orderPlaced')),
            ],
        ),
    ]
