# Generated by Django 3.0 on 2020-09-13 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0013_auto_20200912_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dealenddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 4, 32, 6, 22221)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 13, 4, 32, 6, 23220)),
        ),
    ]
