# Generated by Django 3.0 on 2020-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200725_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedpeople',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
